---
  - name: Delete default route
    blockinfile:
      path: /etc/netplan/50-cloud-init.yaml
      insertafter: '            dhcp4: true'
      block: |
        #Insert from ansible
                    dhcp4-overrides:
                        use-routes: false
  - name: Add default route
    blockinfile:
      path: /etc/netplan/50-vagrant.yaml
      insertafter: '      - 192.168.255.10/30'
      block: |
        #Insert from ansible
              routes:
                - to: 192.168.0.2
                  via: 192.168.254.2
  - name: Netplan apply
    shell: netplan apply
